# Generated by Django 3.2.7 on 2021-09-11 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('balance', models.FloatField(default=0.0, verbose_name='Баланс')),
                ('number', models.CharField(max_length=16, verbose_name='Номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='CashInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('closed', models.BooleanField(default=False, verbose_name='Заапрос выполнен')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashin_requests', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Запрос на пополнение',
                'verbose_name_plural': 'Запросы на пополнение',
            },
        ),
        migrations.CreateModel(
            name='CashInTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('requested_amount', models.FloatField(verbose_name='Сумма пополнения')),
                ('received_amount', models.FloatField(verbose_name='Фактически пополнено')),
                ('received_amount_raw', models.FloatField(blank=True, null=True, verbose_name='Фактически пополнено (без комиссии)')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashin_transactions', to='accountant.card', verbose_name='Карта')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accountant.cashinrequest', verbose_name='Запрос на пополнение')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('replenishment_percent', models.FloatField(default=0.0, verbose_name='Процент за пополнение')),
                ('withdrawal_percent', models.FloatField(default=0.0, verbose_name='Процент за снятие')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_types', to='accountant.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Тип карты',
                'verbose_name_plural': 'Типы карт',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accountant.cardtype', verbose_name='Тип карты'),
        ),
        migrations.AddField(
            model_name='card',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
