# Generated by Django 3.2.7 on 2021-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinrequest',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Запрос выполнен'),
        ),
        migrations.AlterField(
            model_name='cashintransaction',
            name='received_amount',
            field=models.FloatField(default=0.0, verbose_name='Фактически пополнено'),
        ),
        migrations.AlterField(
            model_name='cashintransaction',
            name='received_amount_raw',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Фактически пополнено (без комиссии)'),
        ),
    ]
